{{ if  .Values.grpc.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    delphai-subdomain: {{ .Release.Name }}.grpc
    'external-dns.alpha.kubernetes.io/cloudflare-proxied': 'false'
spec:
  template:
    metadata:
      annotations:
        'autoscaling.knative.dev/target': '{{ .Values.concurrency }}'
        'autoscaling.knative.dev/minScale': '{{ .Values.minScale }}'
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - name: h2c
              containerPort: {{ .Values.grpc.port }}
{{ end }}
---
{{ if  .Values.http.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  namespace: {{ .Release.Namespace }}
  annotations:
    delphai-subdomain: {{ .Release.Name }}
    'external-dns.alpha.kubernetes.io/cloudflare-proxied': 'true'
spec:
  template:
    metadata:
      annotations:
        'autoscaling.knative.dev/target': '{{ .Values.concurrency }}'
        'autoscaling.knative.dev/minScale': '{{ .Values.minScale }}'
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - containerPort: {{ .Values.http.port }}
{{ end }}