apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: translation-grpc-public
  namespace: translation
spec:
  gateways:
    - istio-system/grpc-gateway
  hosts:
    - translation.grpc.delphai.dev

  http:
    - route:
        - destination:
            host: translation.translation.svc.cluster.local
            port:
              number: 8080