apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}