{{ if $.Values.rabbitmq.enabled }}
{{ if index $.Values.buildMetadata.labels "com.delphai.image.release" }}

{{ $queueName := tpl $.Values.rabbitmq.queueName $ }}

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: {{ $.Release.Namespace | quote }}
  name: {{ $.Release.Name | quote }}
spec:
  minReplicaCount: 1
  maxReplicaCount: {{ $.Values.rabbitmq.maxReplicaCount }}
  scaleTargetRef:
    name: {{ $.Release.Name | quote }}
  triggers:
  - type: rabbitmq
    metadata:
      queueName: {{ $queueName | quote }}
      mode: QueueLength
      value: {{ $.Values.rabbitmq.scaleOnQueueLength | quote}}
    authenticationRef:
      name: "rabbitmq-connection-string-{{ $.Release.Name }}"

{{ end }} {{/* if index $.Values.buildMetadata.labels "com.delphai.image.release" */}}
{{ end }} {{/* if $.Values.rabbitmq.enabled */}}
