{{ if $.Values.autoscaling.enabled }}
{{ if index $.Values.buildMetadata.labels "com.delphai.image.release" }}

{{ $queueName := tpl $.Values.autoscaling.queueName $ }}

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: {{ $.Release.Namespace | quote }}
  name: {{ $.Release.Name | quote }}
spec:
  minReplicaCount: 1
  maxReplicaCount: {{ $.Values.autoscaling.maxReplicaCount }}
  scaleTargetRef:
    name: {{ $.Release.Name | quote }}
  triggers:
  - type: rabbitmq
    metadata:
      queueName: {{ $queueName | quote }}
      mode: QueueLength
      value: {{ $.Values.autoscaling.scaleOnQueueLength | quote}}
      hostFromEnv: "RABBITMQ_CONNECTION_STRING"

{{ end }} {{/* if index $.Values.buildMetadata.labels "com.delphai.image.release" */}}
{{ end }} {{/* if $.Values.autoscaling.enabled */}}
