{{ $enabled := or $.Values.autoscaling.rabbitmq.enabled }}

{{ if $enabled }}
{{ if index $.Values.buildMetadata.labels "com.delphai.image.release" }}

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: {{ $.Release.Namespace | quote }}
  name: {{ $.Release.Name | quote }}
spec:
  minReplicaCount: {{ $.Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ $.Values.autoscaling.maxReplicaCount }}
  scaleTargetRef:
    name: {{ $.Release.Name | quote }}

  triggers:
  {{ if $.Values.autoscaling.rabbitmq.enabled }}
  - type: rabbitmq
    metadata:
      hostFromEnv: "RABBITMQ_CONNECTION_STRING"
      queueName: {{ tpl $.Values.autoscaling.rabbitmq.queueName $ | quote }}
      mode: QueueLength
      value: {{ $.Values.autoscaling.rabbitmq.value | quote}}
  {{ end }} {{/* if $.Values.autoscaling.rabbitmq.enabled */}}

{{ end }} {{/* if index $.Values.buildMetadata.labels "com.delphai.image.release" */}}
{{ end }} {{/* if $enabled */}}
