{{ range $portConf := $.Values.ports }}
{{ if or (eq $portConf.enabled nil) $portConf.enabled }}
{{/* declare services only of at least one port is enabled using "range-if-break" */}}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: "{{ $.Release.Name }}"
  ports:
    {{ range $portName, $portConf := $.Values.ports }}
    {{ if or (eq $portConf.enabled nil) $portConf.enabled }}
    - name: {{ $portName | quote }}
      port: {{ $portConf.port }}
      targetPort: {{ $portConf.port }}
    {{ end }} {{/* if or (eq $portConf.enabled nil) $portConf.enabled */}}
    {{ end }} {{/* range ports */}}

{{ if or (eq $.Values.ports.grpc.enabled nil) $.Values.ports.grpc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-grpc"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    helm.sh/release: "{{ $.Release.Name }}"
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: "{{ $.Release.Name }}"
  ports:
    - name: "grpc"
      port: 80
      targetPort: {{ $.Values.ports.grpc.port }}
{{ end }} {{/* if or (eq $.Values.ports.grpc.enabled nil) $.Values.ports.grpc.enabled */}}

{{ break }} {{/* range */}}
{{ end }} {{/* if or (eq $portConf.enabled nil) $portConf.enabled */}}
{{ end }} {{/* range */}}
