apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
    
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: true
      volumes:
        {{- range $fileShare := .Values.fileShares }}
        - name: {{ $fileShare }}
          azureFile:
            secretName: azure-storage
            shareName: {{ $fileShare }}
            readOnly: true
        {{- end }}
      containers:
        - imagePullPolicy: Always
          image: {{ .Values.image }}
          name: {{ .Release.Name }}
          volumeMounts:
            {{- range $fileShare := .Values.fileShares }}
            - name: {{ $fileShare }}
              mountPath: /app/data
            {{- end }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
            - name: h2c
              containerPort: {{ .Values.grpcPort }}