{{ if .Values.isPublic }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{ if gt ( len .Values.domains ) 1 }} 
    external-dns.alpha.kubernetes.io/target: in.{{ .Values.domains[0] }}
  {{ else if if lt ( len .Values.domains ) 1 }}
    external-dns.alpha.kubernetes.io/target: in.{{ .Values.domains }}
  {{ end }}

spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
    {{ if ne ( len .Values.domains ) 0 }}
      {{- range $domain := .Values.domains }}
        {{ if .Values.isUi }}
    - {{ .Release.Name }}.{{ $domain }}
    {{ else }}
    - api.{{ $domain }}
      {{ end }}
      {{ -end }}
      {{ end }}
    
  http:
    - match:
        - uri:
            {{ if .Values.isUi }}
            prefix: '/'
            {{ else }}
            prefix: '/{{ .Release.Name }}/'
            {{ end }}
        {{ if not .Values.isUi }}
        # required because of https://github.com/istio/istio/issues/8076
        - uri:
            exact: '/{{ .Release.Name }}'
        {{ end }}
      {{ if not .Values.isUi }}
      rewrite:
        uri: '/'
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}
      {{ end }}
      route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.httpPort }}
{{ end }}