apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
    {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
    - api.{{ $d }}
    {{- end }}
    {{ end }}
    {{ if eq (len $.Values.domains ) 0 }}
    - api.{{ .Values.domain }}
    {{ end }}
  http:
    - match:
        - uri:
            prefix: '/{{ .Release.Name }}/'
        # required because of https://github.com/istio/istio/issues/8076
        - uri:
            exact: '/{{ .Release.Name }}'
      rewrite:
        uri: '/'
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}
      route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.httpPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-grpc-public
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - istio-system/grpc-gateway
  hosts:
    {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
    - {{ .Release.Name }}.grpc.{{ $d }}
    {{- end }}
    {{ end }}
    {{ if eq (len $.Values.domains ) 0 }}
    - {{ .Release.Name }}.grpc.{{ .Values.domain }}
    {{ end }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.grpcPort }}