apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
    - name: h2c
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}