{{ if .Values.train }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          {{ if .Values.gpu }}
          resources:
            limits:
            nvidia.com/gpu: {{ .Values.gpu_units }}
          {{ end }}
      restartPolicy: OnFailure      
{{ end }}
