{{ if .Values.isPublic }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-serving/knative-ingress-gateway
  hosts: 
    - api.{{ .Values.domain }}
  http:
    - match:
        - uri:         
            prefix: '/{{ .Release.Name }}/'       
        # required because of https://github.com/istio/istio/issues/8076
        - uri:
            exact: '/{{ .Release.Name }}'
      rewrite:
        uri: '/'
        {{ if eq $.Values.delphaiEnvironment "review" }}
        authority: {{ .Release.Name }}.{{ .Values.domain }}
        {{ else }}
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}.internal
        {{ end }}
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
    {{ if .Values.enable_cors }}
      corsPolicy:
        allowOrigins:
        - exact: https://app.delphai.com
        allowMethods: [GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH]
        allowCredentials: true
        allowHeaders: [Origin, Content-Type, Accept, Authorization, X-Request-With, X-GENERAL-TOKEN, x-grpc-web, grpc-timeout]
        maxAge: "24h"
    {{ end }}
{{ if .Values.grpcPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-grpc-public
  namespace: {{ .Release.Namespace }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-serving/knative-ingress-gateway
  hosts:
    - {{ .Release.Name }}.grpc.{{ .Values.domain }}
  http:
    - rewrite:
        authority: {{ .Release.Name }}-grpc-public.{{ .Release.Namespace }}.internal
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
    {{ if .Values.enable_cors }}
      corsPolicy:
        allowOrigins:
        - exact: https://app.delphai.com
        allowMethods: [GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH]
        allowCredentials: true
        allowHeaders: [Origin, Content-Type, Accept, Authorization, X-Request-With, X-GENERAL-TOKEN, x-grpc-web, grpc-timeout]
        maxAge: "24h"
    {{ end }}
{{ end }}
{{ end }}
