apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  jobTargetRef:
    parallelism: {{ .Values.autoscaling.parallelism }}
    completions: 1
    activeDeadlineSeconds: {{ .Values.deadline }}
    backoffLimit: {{ .Values.retries }}
    template:
      metadata:
        labels:
          app: {{ .Release.Name }}
        annotations:
          'prometheus.io/port': '9191'
          'prometheus.io/scrape': 'true'
      spec:
        tolerations:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: "Equal"
            value: "spot"
            effect: "NoSchedule"
        containers:
          - name: {{ .Release.Name }}
            image: {{ .Values.image }}
            imagePullPolicy: Always
            env:
              - name: DELPHAI_ENVIRONMENT
                value: {{ .Values.delphaiEnvironment }}
              - name: AZURE_STORAGE_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: azure-storage-production
                    key: connection-string

  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  successfulJobsHistoryLimit: 50
  failedJobsHistoryLimit: 50
  maxReplicaCount: {{ .Values.autoscaling.parallelism }}
  scalingStrategy:
    strategy: default
  triggers:
    - type: azure-queue
      metadata:
        queueName: {{ .Release.Name }}
        queueLength: "{{ .Values.autoscaling.queueLength }}"
        connectionFromEnv: AZURE_STORAGE_CONNECTION_STRING
