apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
    
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: acr-credentials
      automountServiceAccountToken: true
      containers:
        - imagePullPolicy: Always
          image: {{ .Values.image }}
          name: {{ .Release.Name }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
            - name: h2c
              containerPort: {{ .Values.grpc.port }}
