{{ if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.monitoring
      metricName: delphai_requests_per_sec
      threshold: '{{ .Values.autoscaling.threshold }}'
      query: sum(rate(delphai_request_count_total{app="{{ .Release.Name }}"}[2m]))
{{ end }}