{{ if .Values.http.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
---
{{ end }}
{{ if .Values.grpc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc-port
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
---
{{ end }}