{{ if .Values.http.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
    {{ if and .Values.http.public .Values.http.publicWithOAuth }}
    - name: oauth-proxy
      port: {{ .Values.http.oAuthProxyPort }}
      targetPort: {{ .Values.http.oAuthProxyPort }}
    {{ end }}
{{ end }}

{{ if .Values.grpc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc-port
      port: 80
      targetPort: {{ .Values.grpc.port }}
{{ end }}
