{{- range $.Values.steps }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}"
  namespace: {{ $.Release.Namespace }}
  annotations:
    consumerGroup: "{{ $.Release.Name }}.{{ .name }}"
  labels:
    app: {{ $.Release.Name }}
    release: "{{ $.Release.Name }}-{{ .name }}"
    pipeline: {{ $.Release.Name }}
spec:
  serviceName: "{{ $.Release.Name }}-{{ .name }}"
  replicas: {{ $.Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      release: "{{ $.Release.Name }}-{{ .name }}"
  template:
    metadata:
      annotations:
        consumerGroup: "{{ $.Release.Name }}.{{ .name }}"
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
      labels:
        app: {{ $.Release.Name }}
        release: "{{ $.Release.Name }}-{{ .name }}"
        pipeline: {{ $.Release.Name }}
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: {{ $.Release.Name }}
          image: {{ $.Values.image }}
          imagePullPolicy: 
          command:
            - python
            - /app/src/main.py
            - start
            - --steps
            - {{ .name }}
          resources:
{{ toYaml $.Values.resources | indent 12 }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ $.Values.delphaiEnvironment }}
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
---
{{- end }}