{{- if .Values.deployGateway }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: "api.{{ .Values.domain }}"
      http:
        paths:
          - path: "/{{ .Release.Name }}/(.*)"
            backend:
              serviceName: {{ .Release.Name }}
              {{ if eq .Values.authRequired true }}
              servicePort: {{ .Values.authPort }}
              {{ else }}
              servicePort: {{ .Values.gatewayPort }}
              {{ end }}
{{- end }}