image:      # "delphai.azurecr.io/..."
domain:     # "delphai.black"
minReplicas: 1
delphaiEnvironment: development
subdomain: api
autoscaling:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 30
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 10
  threshold: 100
resources: {}
http:
  enabled: true
  port: 7070
  public: true
  publicWithOAuth: false
  oAuthProxyPort: 37070
  oAuthRequireOneOfRoles: []
grpc:
  enabled: true
  port: 8080
  public: true
env: []
gpu: false
mountPath: /app/data
fileShares: []
onePodMaxPerNodePerApp: false
preferGpu: false
resources:
  requests:
    memory: 300Mi
  limits:
    memory: 2500Mi
