image: delphai.azurecr.io/projects:latest
domain: delphai.black
minReplicas: 1
delphaiEnvironment: development
autoscaling:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 30
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 10
  threshold: 100
resources: {}
http:
  enabled: true
  port: 7070
  public: true
grpc:
  enabled: true
  port: 8080
  public: true
  services:
    - delphai.projects.Projects
