image: kennethreitz/httpbin
httpPort: 80
domain: delphai.black
domains: ""
replicas: 3
delphaiEnvironment: development
subdomain: sub
limitsCpu: 1000m
limitsMemory: 500Mi
requestsCpu: 100m
requestsMemory: 100Mi
