apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    delphai-subdomain: {{ .Release.Name }}
    'external-dns.alpha.kubernetes.io/cloudflare-proxied': 'true'
spec:
  template:
    metadata:
      annotations:
        'autoscaling.knative.dev/target': '{{ .Values.concurrency }}'
        'autoscaling.knative.dev/minScale': '{{ .Values.minScale }}'
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - image: {{ .Values.image }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          args: ["--workers","1", "--enable-microbatch"]
          ports:
            - containerPort: {{ .Values.httpPort }}
