apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: '{{ .Values.concurrency }}'
        autoscaling.knative.dev/minScale: '{{ .Values.minScale }}'.
        autoscaling.knative.dev/maxScale: "30"
    spec:
      containers:
        - image: {{ .Values.image }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          args: ["--workers","1", "--enable-microbatch"]
          ports:
            - containerPort: {{ .Values.httpPort }}
