apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
    - models.{{ .Values.domain }}
  http:
    - match:
        - uri:
            prefix: '/{{ .Release.Name }}/'
        - uri:
            exact: '/{{ .Release.Name }}'     
      rewrite:
        uri: '/'
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}.internal     
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
