apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-serving/knative-ingress-gateway
  hosts:
  {{ if eq $.Values.delphaiEnvironment "common" }}
    - models.{{ .Values.domain }}
  {{ else if eq $.Values.delphaiEnvironment "hybrid" }}
    - ml.{{ .Values.domain }}
  {{ end }}
  http:
    - match:
        - uri:
            prefix: '/{{ .Release.Name }}/'
        - uri:
            exact: '/{{ .Release.Name }}'     
      rewrite:
        uri: '/'
        {{ if eq $.Values.delphaiEnvironment "common" }}
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}.internal
        {{ else if eq $.Values.delphaiEnvironment "hybrid" }}
        authority: {{ .Release.Name }}.{{ .Values.domain }}
        {{ end }}
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80