apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    delphai-subdomain: {{ .Release.Name }}
    'external-dns.alpha.kubernetes.io/cloudflare-proxied': 'true'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '{{ .Values.concurrency }}'
        autoscaling.knative.dev/minScale: '{{ .Values.minScale }}'
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
    spec:
      containers:
        - image: {{ .Values.image }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - containerPort: {{ .Values.httpPort }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '{{ .Values.concurrency }}'
        autoscaling.knative.dev/minScale: '{{ .Values.minScale }}'
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
    spec:
      timeoutSeconds: 600
      containers:
        - image: {{ .Values.image }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - name: h2c
              containerPort: {{ .Values.grpcPort }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc-public
  namespace: {{ .Release.Namespace }}
  annotations:
    delphai-subdomain: {{ .Release.Name }}.grpc
    'external-dns.alpha.kubernetes.io/cloudflare-proxied': 'false'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '{{ .Values.concurrency }}'
        autoscaling.knative.dev/minScale: '{{ .Values.minScale }}'
        'prometheus.io/port': '9191'
        'prometheus.io/scrape': 'true'
    spec:
      timeoutSeconds: 600
      containers:
        - image: {{ .Values.image }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - name: h2c
              containerPort: {{ .Values.grpcPort }}