apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '{{ .Values.concurrency }}'
    spec:
      containers:
        - image: {{ .Values.image }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - containerPort: {{ .Values.httpPort }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '{{ .Values.concurrency }}'
        {{ if .Values.isRunner }}
        autoscaling.knative.dev/minScale: '1'
        {{ end }}
    spec:
      timeoutSeconds: 600
      volumes:
        {{- range .Values.fileShares }}
        - name: {{ .name }}
          azureFile:
            secretName: azure-storage
            shareName: {{ .name }}
            readOnly: true
        {{- end }}
      containers:
        - image: {{ .Values.image }}
          volumeMounts:
            {{- range .Values.fileShares }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          env:
            - name: DELPHAI_ENVIRONMENT
              value: {{ .Values.delphaiEnvironment }}
          ports:
            - name: h2c
              containerPort: {{ .Values.grpcPort }}