{{ if .Values.isPublic }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.isUi }}
  external-dns.alpha.kubernetes.io/target: in.${domain}
  {{ end }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
    {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
    {{ if .Values.isUi }}
    - {{ .Release.Name }}.{{ $d }}
    {{ else }}
    - api.{{ $d }}
    {{ end }}
    {{- end }}
    {{ end }}

    {{ if eq (len $.Values.domains ) 0 }}
    {{ if .Values.isUi }}
    - {{ .Release.Name }}.{{ .Values.domain }}
    {{ else }}
    - api.{{ .Values.domain }}
    {{ end }}
    {{ end }}
  http:
    - match:
        - uri:
            {{ if .Values.isUi }}
            prefix: '/'
            {{ else }}
            prefix: '/{{ .Release.Name }}/'
            {{ end }}
        {{ if not .Values.isUi }}
        # required because of https://github.com/istio/istio/issues/8076
        - uri:
            exact: '/{{ .Release.Name }}'
        {{ end }}
      {{ if not .Values.isUi }}
      rewrite:
        uri: '/'
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}
      {{ end }}
      route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.httpPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-grpc-public
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - istio-system/grpc-gateway
  hosts:
    {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
    - {{ .Release.Name }}.grpc.{{ $d }}
    {{- end }}
    {{ end }}
    {{ if eq (len $.Values.domains ) 0 }}
    - {{ .Release.Name }}.grpc.{{ .Values.domain }}
    {{ end }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.grpcPort }}
{{ end }}