
name: destroy-review

on: [delete]

jobs:
  destroy-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Uninstall
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az login --service-principal --username ${{ secrets.ARM_CLIENT_ID_REVIEW }} --password ${{ secrets.ARM_CLIENT_SECRET_REVIEW }} --tenant ${{ secrets.ARM_TENANT_ID_REVIEW }}
          az aks get-credentials -n delphai-review -g tf-cluster
          sudo snap install helm --classic
          helm repo add delphai https://delphai.github.io/helm-charts && helm repo update
          helm uninstall ${{ env.REPOSITORY_NAME }}-${{ env.GITHUB_EVENT_REF_SLUG }} -n ${{ env.REPOSITORY_NAME }}