apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: contour-external
    {{ if eq $.Values.delphaiEnvironment "review" }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{ .Values.domain }}
    {{ else }}
    external-dns.alpha.kubernetes.io/target: in.{{ .Values.domain }}
    {{ end }}
spec:
  rules:
  
   {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
      {{ if $.Values.subdomain }}
    - host: {{ $.Values.subdomain }}.{{ $d }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}
                port: {{ $.Values.httpPort }}
      {{ else }}
    - host: {{ $.Release.Name }}.{{ $d }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}
                port: {{ $.Values.httpPort }}
      {{ end }}
    {{- end }}
  {{ end }}
  {{ if eq (len $.Values.domains ) 0 }}
    {{ if $.Values.subdomain }}
    - host: {{ $.Values.subdomain }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}
                port: {{ $.Values.httpPort }}
    {{ else }}
    - host: {{ $.Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}
                port: {{ $.Values.httpPort }}
    {{ end }}
  {{ end }}