apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: istio
    {{ if ne ( len .Values.domains ) 0 }}
      {{- range $domain := .Values.domains }}
    external-dns.alpha.kubernetes.io/target: in.{{ $domain }}
      {{ end }}
    {{ -end }}
spec:
  rules:
    {{ if ne ( len .Values.domains ) 0 }}
      {{- range $domain := .Values.domains }}
    - host: {{ .Release.Name }}.{{ $domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.httpPort }}
    {{ end }}
    {{ -end }}
