apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
  
   {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
      {{ if $.Values.subdomain }}
    - host: {{ $.Values.subdomain }}.{{ $d }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.httpPort }}
      {{ else }}
    - host: {{ $.Release.Name }}.{{ $d }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.httpPort }}
      {{ end }}
    {{- end }}
  {{ end }}
  {{ if eq (len $.Values.domains ) 0 }}
    {{ if $.Values.subdomain }}
    - host: {{ $.Values.subdomain }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port: 
                  number: {{ $.Values.httpPort }}
    {{ else }}
    - host: {{ $.Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.httpPort }}
    {{ end }}
  {{ end }}