apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: istio
    external-dns.alpha.kubernetes.io/target: in.{{ .Values.domain }}
spec:
  rules:
  
   {{ if gt (len $.Values.domains ) 0 }}
    {{- range $d := .Values.domains }}
    - host: {{ $.Release.Name }}.{{ $d }}
      http:
        paths:
          - backend:
              serviceName: {{ $.Release.Name }}
              servicePort: {{ $.Values.httpPort }}
    {{- end }}
  {{ end }}
  {{ if eq (len $.Values.domains ) 0 }}
    - host: {{ $.Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ $.Release.Name }}
              servicePort: {{ $.Values.httpPort }}
  {{ end }}